M48
; DRILL file {KiCad 9.0.6-unknown-1000.20251110git96868b2.fc41} date 2025-12-16T17:43:41-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-16T17:43:41-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-unknown-1000.20251110git96868b2.fc41
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.600
%
G90
G05
T1
X158.895Y-78.86
X158.895Y-84.64
T2
X133.75Y-64.5
T3
X159.0Y-70.585
X159.665Y-44.25
T4
X133.75Y-89.5
M30
