M48
; DRILL file {KiCad 9.0.7-unknown-1000.20260124git33f2886.fc43} date 2026-02-08T17:52:06-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-08T17:52:06-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-unknown-1000.20260124git33f2886.fc43
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.600
%
G90
G05
T1
X158.895Y-78.86
X158.895Y-84.64
T2
X133.75Y-64.5
T3
X159.0Y-70.585
X159.665Y-44.25
T4
X133.75Y-89.5
M30
