M48
; DRILL file {KiCad 9.0.6} date 2026-04-13T01:54:56-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-13T01:54:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.300
%
G90
G05
T1
X33.223Y-136.703
X73.203Y-136.703
T2
X5.944Y-5.893
X100.482Y-5.944
M30
